export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_DATA_TROTOAR = 'CREATE_DATA_TROTOAR';
export const UPDATE_DATA_TROTOAR = 'UPDATE_DATA_TROTOAR';
export const DELETE_DATA_TROTOAR = 'DELETE_DATA_TROTOAR';
export const FETCH_DATA_TROTOAR = 'FETCH_DATA_TROTOAR';
export const FETCH_DATA_TROTOARS = 'FETCH_DATA_TROTOARS';

export const CREATE_DATA_WILAYAH = 'CREATE_DATA_WILAYAH';
export const UPDATE_DATA_WILAYAH = 'UPDATE_DATA_WILAYAH';
export const DELETE_DATA_WILAYAH = 'DELETE_DATA_WILAYAH';
export const FETCH_DATA_WILAYAH = 'FETCH_DATA_WILAYAH';